name: TownyHerochatLink
author: L337Lobster
website: http://dev.bukkit.org/bukkit-plugins/townyherochatlink
main: com.llfrealms.THChatLink.THCLink
depend: [Towny,Herochat,Vault]
version: 2.0

commands:
    thcsave:
       description: save config.
       aliases: thcs
       permission: thcl.save
       permission-message: You do not have permission for this command
       usage: /<command>
    thcload:
       description: reload config.
       aliases: thcl
       permission: thcl.save
       permission-message: You do not have permission for this command
       usage: /<command>
    thcrefresh:
        description: Refresh town and nation channels (i.e. create any that aren't made yet)
        aliases: thcr
        permission: thcl.refresh
        permission-message: You do not have permission for this command
        usage: /<command>
    thcgroups:
        description: no description
        aliases: thcg
        usage: /<command>
permissions:
    thcl.*:
        description: Gives access to all permissions.
        default: op
        children:
            thcl.save: true
            thcl.load: true
            thcl.refresh: true
    thcl.load:
        description: Allows the user to reload the config file
        default: false
    thcl.save:
        description: Allows the user to save the config file
        default: false
    thcl.refresh:
        description: Allows the user to refresh the channels
        default: false